### ISSUE TITLE
No H1 found when in <nav> tag

### ISSUE THREAD

**Issue by adrien-delhorme** [kapt-labs/django-check-seo#30]
**Describe the bug**
When the H1 is in a `<nav>` tag, django-check-seo does not find it.

```
<body>
  <nav>
    <h1>not found</h1>
  </nav>
</body>
```

**Comment by corentinbettiol** [comment]
We used to remove all `nav` & `footer` tags, but with the solution in #35 we should not encounter this problem anymore.
