### ISSUE TITLE
Lack of affordance

### ISSUE THREAD

**Issue by adrien-delhorme** [kapt-labs/django-check-seo#31]
Some users do not know that they can click on a check result to show more informations:

- check result lines have no affordance (no button, no link, no icon)
- mouse cursor when hovering a check result line, is not usual

**Comment by corentinbettiol** [comment]
Yeah using the `help` cursor only means that *Help information is available* (*[src](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)*).

What can we do to make it clearer? Add an arrow?

![image](https://user-images.githubusercontent.com/45763865/75541669-9bf0f500-5a1e-11ea-9c3b-a5c806be9e1e.png)

**Comment by corentinbettiol** [comment]
Will add default summary arrow in future release.

**Comment by corentinbettiol** [comment]
![image](https://user-images.githubusercontent.com/45763865/75671188-782bea00-5c7e-11ea-9584-4d74b6c7ceeb.png)

Styling will only work for chrome & firefox (marker element is in draft for ie/safari...).

IE/Safari will render the arrows like this:

![image](https://user-images.githubusercontent.com/45763865/75671295-b6290e00-5c7e-11ea-8354-5c2ca0980d3a.png)

**Comment by corentinbettiol** [comment]
Fixed in 8ecb9b19fb38efcb02fbd7b36d232f18b21c33aa.
