### ISSUE TITLE
Max retries exceeded 

### ISSUE THREAD

**Issue by memetics19** [kapt-labs/django-check-seo#39]
I deployed a djangocms in heroku and checked the SEO check but it returned this error `HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //astaqc-djangocms.herokuapp.com//en/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f45e24480b8>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

Here is the screenshot 
![image](https://user-images.githubusercontent.com/50732218/89707760-c1e7d180-d98e-11ea-9d6b-db0d884eeb1d.png)

**Comment by corentinbettiol** [comment]
@memetics19 First of all, thank you for using django check seo :)

Then, what are your settings, please ?
I see that django-check-seo is trying to reach `https://astaqc-djangocms.herokuapp.com//en/` (note the additional `/` before `/en/`), this is not a normal behavior.

**Comment by memetics19** [comment]
@corentinbettiol  I have resolved it, in django cms I have added link this  `https://astaqc-djangocms.herokuapp.com`  but I found that `https` is not required to add in the site. When I removed `https` it's resolved

**Comment by corentinbettiol** [comment]
Nice, glad that your issue was solved :)
