### ISSUE TITLE
it is possible to use without djangocms?

### ISSUE THREAD

**Issue by CARocha** [kapt-labs/django-check-seo#41]
it is possible to use without djangocms?
I have a handmade website, and I wanted to see how my SEO is if it is correct or has problems, open some way to install and use this package for sites that are not built from djangocms

**Comment by corentinbettiol** [comment]
It is not explicitly written on the readme, but as I said on [this dev.to](https://dev.to/oluwakayodea/comment/12fpe) post its possible to use django-check-seo without django-cms.

All it does if django-cms is installed is to add a button on the topbar. If you do not use django-cms, you just have to go the the `yourwebsite.ext/django-check-seo/?page=/` page to use django-check-seo and see the seo results for your homepage.

**Comment by CARocha** [comment]
@corentinbettiol great thank you!
