### ISSUE TITLE
Failed parse

### ISSUE THREAD

**Issue by ilamarche** [kapt-labs/django-check-seo#42]
**Describe the bug**
Failed requests.exceptions.InvalidURL: Failed to parse: http://127.0.0.1:8000b'/fr/'

**To Reproduce**
Django<3.1
django-cms>=3.7,<3.8
django-check-seo==0.3.6

**Expected behavior**
Expected http://127.0.0.1:8000/fr/

**Desktop :**
 - Python 3.8.5

** Temporary Fix **
Override IndexView and add at line 30 : 

            page = self.request.GET.get("page", None)
            page = page[2:(len(page) - 1)]
            full_url = (
                    protocol
                    + Site.objects.get_current().domain
                    + page
            )

**Comment by corentinbettiol** [comment]
@ilamarche I will investigate this, thank you.

> This is the [current code](https://github.com/kapt-labs/django-check-seo/blob/master/django_check_seo/views.py#L32-L36):
> ```python
> full_url = (
>     protocol
>     + Site.objects.get_current().domain
>     + self.request.GET.get("page", None)
> )
> ```
> 
> This is your code:
> ```python
> page = self.request.GET.get("page", None)
> page = page[2:(len(page) - 1)]
> full_url = (
>     protocol
>     + Site.objects.get_current().domain
>     + page
> )
> ```
