### ISSUE TITLE
Send DJANGO_CHECK_SEO_AUTH along with the request in case of redirect [3xx]

### ISSUE THREAD

**Issue by rhenanbartels** [kapt-labs/django-check-seo#43]
Hi! 

First of all, I would like to thank you for the great work! This is a very helpful package and It saved us a lot of time on enhancing the SEO of our posts.

Recently, we started using the `DJANGO_CHECK_SEO_AUTH` to use auth credentials along with the request. But for reasons we don't fully control, the DNS server is redirecting us to another URL.  

In this scenario, because of a [characteristic of the requests](https://github.com/psf/requests/issues/2949) package, the `HTTP_AUTHORATION` is not sent in the redirect request (after a 3xx) and we end up with a 404 (the view wasn't able to authenticate the request).

I was wondering if the [request made by `django_check_seo` ](https://github.com/kapt-labs/django-check-seo/blob/7aedb76ae5f576798b9d491cd3a5ec84a6777068/django_check_seo/views.py#L46) could check for a **3xx**
status code and follow the new URL location with the  `DJANGO_CHECK_SEO_AUTH` information.

Here is a simple example:

```python
import requests

r = requests.get(
    URL, 
    auth=(
        settings.DJANGO_CHECK_SEO_AUTH["user"],
        settings.DJANGO_CHECK_SEO_AUTH["pass"],
     ),
    allow_redirects=False
)

if 300 < r.status_code < 400:
    r = requests.get(
    r.headers['location'], 
    auth=(
        settings.DJANGO_CHECK_SEO_AUTH["user"],
        settings.DJANGO_CHECK_SEO_AUTH["pass"],
     ),
)
```
## Versions
- Python 3.6.8
- django-check-seo==0.3.6
- requests==2.18.4

Thank you very much,
[]s

**Comment by corentinbettiol** [comment]
Hello, thank you for the kind words and for the detailed explanation!

I think that I will add this as a setting (which will default to False, since it's relative to a [CVE](https://web.archive.org/web/20201025080330/https://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2014-1829)), and a warning in the README.
