### ISSUE TITLE
Running Without CMS or Installation errors

### ISSUE THREAD

**Issue by virajkothari7** [kapt-labs/django-check-seo#46]
I am not sure whether this will be helpfull to others, but this is what I did after going through some issues while installing this. 

You can follow the installation, and after installation make sure this are the settings present.
 > add 'django.contrib.sites' to INSTALLED_APPS
 > SITE_ID = 1

This step is important if running without CMS  
> Go to template 'default.html' in site packages of installed apps
> remove 'cms_tag'
> save it 
> access your page seo by,
     >.   base.domain/django-check-seo/?page=/page_extnsn

<br>
<br>
Hope this helps!

**Comment by corentinbettiol** [comment]
Thank you, I will update the README with the information you provided in order to make install easier for people who don't use django-cms !
