### ISSUE TITLE
'default_app_config' is deprecated

### ISSUE THREAD

**Issue by DmytroLitvinov** [kapt-labs/django-check-seo#60]
Starting from [Django v4.1 'default_app_config' is deprecated](https://docs.djangoproject.com/en/5.0/releases/4.1/#features-removed-in-4-1) 

As a possible fix:
```
if django.VERSION < (3, 2):
    default_app_config = "django_check_seo.apps.DjangoCheckSEOConfig"
```

**Comment by corentinbettiol** [comment]
I published your fix in the version [0.6.5 on pypi](https://pypi.org/project/django-check-seo/0.6.5/#files)!
